[project]
name = "dbt-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.9.6",
    "dbt-osmosis>=1.1.17",
]
